---
namespace: ivorynomad
name: onepassword
version: 1.0.0

readme: README.md
authors:
- IvoryNomad

description: Ansible collection for 1Password CLI integration
license_file: 'LICENSE'

tags:
- onepassword
- secrets
- security
- vault
- lookup
- cli
- authentication
- password_management

dependencies: {}

repository: https://github.com/IvoryNomad/ansible-onepassword
documentation: https://github.com/IvoryNomad/ansible-onepassword
homepage: https://github.com/IvoryNomad/ansible-onepassword
issues: https://github.com/IvoryNomad/ansible-onepassword/issues

build_ignore:
- .github/
- .gitignore
- .git/
- tests/
- '*.tar.gz'
- '*.log'
- .pytest_cache/
- __pycache__/
- '*.pyc'
- .coverage
- coverage.xml
- .vscode/
- .idea/
